name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install PowerShell
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https software-properties-common
          wget -q "https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb"
          sudo dpkg -i packages-microsoft-prod.deb
          sudo apt-get update
          sudo apt-get install -y powershell
      - name: Install modules
        run: |
          pwsh -NoProfile -Command "Install-Module Pester -Scope CurrentUser -Force"
          pwsh -NoProfile -Command "Install-Module powershell-yaml -Scope CurrentUser -Force"
      - name: Run tests
        run: pwsh -NoProfile -Command "Invoke-Pester -Path tests -CI"
