name: redshield-ci
on:
  push: { branches: [ "main" ] }
  pull_request: { branches: [ "main" ] }
jobs:
  build-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup PowerShell modules
        run: pwsh -NoLogo -NoProfile -Command "Set-PSRepository PSGallery -InstallationPolicy Trusted; Install-Module Pester,PSScriptAnalyzer,powershell-yaml -Force -Scope CurrentUser"
      - name: Lint
        run: |
          pwsh -NoProfile -Command "& {
            Invoke-ScriptAnalyzer -Path ./src -Recurse -Severity Warning,Error
            if ($LASTEXITCODE -ne 0) {
              Write-Error \"Linting failed\"
              exit 1
            }
          }"
      - name: Test
        run: pwsh -NoProfile -Command "Invoke-Pester -Path ./tests -CI"
      - name: Package
        run: pwsh -NoProfile -Command "New-Item -ItemType Directory -Path dist -Force | Out-Null; Compress-Archive -Path src/*,scripts/*,playbooks/*,config/* -DestinationPath dist/RedShield-0.1.0.zip -Force; Get-FileHash dist/RedShield-0.1.0.zip -Algorithm SHA256 | Tee-Object dist/artifact.sha256.txt"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with: { name: redshield-artifacts, path: dist/ }
