name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup PowerShell
        uses: actions/setup-powershell@v1
        with:
          powershell-version: "7.4"
      - name: Install modules
        run: |
          pwsh -NoProfile -Command "Install-Module Pester -Scope CurrentUser -Force"
          pwsh -NoProfile -Command "Install-Module powershell-yaml -Scope CurrentUser -Force"
      - name: Run tests
        run: pwsh -NoProfile -Command "Invoke-Pester -Path tests -CI"
